name: "Post has a factual error"
description: "Open this when a post has a factual error like missing context or outdated or wrong information."
title: "[Post Link]: "
labels: [factual-error]
assignees: "koraxial"
